export const TODO_GET_DATA_SUCCESS = 'TODO_GET_DATA_SUCCESS';
export const TODO_GET_DATA_REQUEST = 'TODO_GET_DATA_REQUEST';
export const TODO_GET_DATA_FAIL = 'TODO_GET_DATA_FAIL';

export const AUTH_GET_DATA_SUCCESS = 'AUTH_GET_ALL_DATA';
export const AUTH_GET_DATA_REQUEST = 'AUTH_GET_DATA_REQUEST';
export const AUTH_GET_DATA_FAIL = 'AUTH_GET_DATA_FAIL';

export const REGISTER_GET_DATA_SUCCESS = 'REGISTER_GET_ALL_DATA';
export const REGISTER_GET_DATA_REQUEST = 'REGISTER_GET_DATA_REQUEST';
export const REGISTER_GET_DATA_FAIL = 'REGISTER_GET_DATA_FAIL';

export const CREATE_TODO_DATA_SUCCESS = 'CREATE_TODO_ALL_DATA';
export const CREATE_TODO_DATA_REQUEST = 'CREATE_TODO_DATA_REQUEST';
export const CREATE_TODO_DATA_FAIL = 'CREATE_TODO_DATA_FAIL';

export const UPDATE_TODO_DATA_SUCCESS = 'UPDATE_TODO_DATA_SUCCESS';
export const UPDATE_TODO_DATA_FAIL = 'UPDATE_TODO_DATA_FAIL';


export const GET_SINGLE_TODO_DATA_SUCCESS = 'GET_SINGLE_TODO_DATA_SUCCESS';
export const GET_SINGLE_TODO_DATA_FAIL = 'GET_SINGLE_TODO_DATA_FAIL';

export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS';
export const DELETE_DATA_FAIL = 'DELETE_DATA_FAIL';
export const DELETE_DATA_DATA_FAIL = 'DELETE_DATA_DATA_FAIL';
